Budget_app
JakariaJishan/Budget-App pull request #5
Opened 2023-06-09 18:10 UTC by JakariaJishan

presentation - https://drive.google.com/file/d/1evbLPkDqLs8VVOE-OF6pT2-hkqDNMNCJ/view?usp=sharing

### Project requirements

#### Design
- You should follow these [design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), including:
  - Colors.
  - Typography: font face, size and weight.
  - Layout: composition and space between elements.

> NOTE: In these design guidelines there are several UIs that you won't need for this exercise; also, some pages are not given a design and you will create them following the design guidelines of the other pages.

Original design idea by [Gregoire Vella on Behance](https://www.behance.net/gregoirevella).

The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

#### Interactions
- Splash screen
  - A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.

- Sign up and log in pages
  - The user should be able to register in the app with full name, email and password (all mandatory).
  - The user can log into the app using email and password.
  - If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

- Home page (categories page)
  - When the user logs in, they are presented with the categories page.
  - For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
  - When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
  - There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

- Transactions page
  - For a given category, the list of transactions is presented, ordered by the most recent.
  - At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
  - There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new category" page
  - The user fills out a form to create a new category, indicating their name and icon (both mandatory).
  - The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new transaction" page
  - The user fills out a form to create a new transaction with:
    - name (mandatory)
    - amount (mandatory)
    - categories (mandatory at least one)
  - The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
  - When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

#### Testing requirements
- Create unit and integration tests for all the most important components of your RoR application.

2023-06-09 18:28 UTC, BenMukebo reviewed
## STATUS: INVALID ❌ 

Hi  @JakariaJishan,

I can't miss felicitating your efforts and energy, you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 

- [ ] You have submitted a project, that did not follow the GitHub flow.
- Since this is a solo Capston Project, The Pull Request should be made from the “feature branch” into the `dev` branch and not the "dev" to the "main". I suggest you change this. 👍🏻 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@BenMukebo) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit.

2023-06-09 18:35 UTC, JakariaJishan commented
Hi @BenMukebo , thank you for your Review. However, I disagree with your invalidation, here is a screenshot of how to correctly follow [Giflow workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow#:~:text=What%20is%20Gitflow%3F,lived%20branches%20and%20larger%20commits.), as you can see below, every feature should reside in its own branch. 👇🏽

![image](https://github.com/JakariaJishan/Budget-App/assets/73704727/99a5109e-7cf6-4962-903e-a55e721b7121)

This is the definition of Feature:

In software development, a feature refers to a distinct and self-contained functionality or characteristic of a software system or application. It represents a specific task or capability that provides value to the users or fulfills a specific requirement.

A complete full-stack project including Database, UI, and all the logic for the actions is clearly not a single Feature but involves several Features, each of those Features needs to be developed in a separated feature-branch according to [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow#:~:text=What%20is%20Gitflow%3F,lived%20branches%20and%20larger%20commits.).

2023-06-09 20:18 UTC, KDlamini requested changes
### Hi @JakariaJishan 🙋‍♀️,  

Great work so far! 💯 
You have done a great job creating a working Budget app using Rails and Devise authentication. 🎊 🥳 
There are some issues that you still need to work on improving your project according to the requirements. You are almost there! 💪🏾 

## HIGHLIGHTS 🌟 

✔️ Good UI implementation
✔️ Good PR title and description
✔️ Models, controllers, migrations, and routes set up correctly
✔️ Database structure follows ERD architecture
✔️ Project is deployed successfully

## Video Presentation 🎥 

✔️  There is a recorded presentation video presenting the features of the project with a maximum length of 5 minutes.
✔️  The video contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
✔️  The video contains a demo of the project, highlighting all the project features.
✖️  The video contains a highlight about a piece of the code the student finds interesting or is proud of making.

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 20:18 UTC, KDlamini commented on app/views/devise/registrations/new.html.erb
> +  <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
In this milestone, you are required to replicate the EXACT [Behance design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=) for the registration page.

- There should be a navbar with a background color `#3778c2` that has a back arrow, a heading "REGISTER", and a "next" button.
- The back arrow should navigate back to the home screen, the "next" button should register a new user.
- The upload picture, full name, email, and password fields should be separated by a border with a light grey color `#EDEDEE`.
- The should be no input labels but placeholders, and no border-left and border-right per input field.

![image](https://github.com/JakariaJishan/Budget-App/assets/38088818/188334b0-94a1-43d8-af6f-ae04c0e584ac)

Your registration form:

![image](https://github.com/JakariaJishan/Budget-App/assets/38088818/9a5ca084-0b96-485c-bb7b-d2af3791276f)

2023-06-09 20:18 UTC, KDlamini commented on app/views/devise/sessions/new.html.erb
> +      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outl
The same thing applies to the login page. Please make sure that your login is an exact match to the [Behance design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=).

Behance design:

![image](https://github.com/JakariaJishan/Budget-App/assets/38088818/4bdf0f95-b72d-4e30-93d7-485e3148a9dd)

Your design:

![image](https://github.com/JakariaJishan/Budget-App/assets/38088818/c80dfcc0-96d6-471f-a799-f8e731be4ddc)

2023-06-09 20:18 UTC, KDlamini commented on app/views/categories/index.html.erb
> +      <% end %>
Well done on the categories page. Categories are created following project requirements and design guidelines!!! 👏🏾 💯 

![image](https://github.com/JakariaJishan/Budget-App/assets/38088818/e7d3d8ce-1195-4bcc-887f-aa58c046f5a7)

2023-06-09 20:18 UTC, KDlamini commented on app/views/categories/show.html.erb
> +    <div class="flex items-center gap-px">
Well done on your transactions page. Design guidelines are followed, and new transaction form follows project requirements!!! 👏🏾💯

![image](https://github.com/JakariaJishan/Budget-App/assets/38088818/fc5c5d11-0e7e-4379-b50f-9e6ea2fe2008)

2023-06-09 20:18 UTC, KDlamini commented on spec/features/category_spec.rb
Great job with the unit and integration tests!!! 💪🏾

![image](https://github.com/JakariaJishan/Budget-App/assets/38088818/19006a3f-8785-4792-a0b9-13682959f48b)

2023-06-09 20:18 UTC, KDlamini commented on README.md
> +
The link to your `issues` page is broken, kindly fix it to make your README more professional.  The repo link used is for a blog-app that does not exist.

2023-06-10 00:24 UTC, vickymarz approved these changes
Hi @JakariaJishan, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- Request changes implemented✅ 
 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 11:38 UTC, merged